language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "deployment-exercise-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: deployed-bananas
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: IlXP0FQBN/k8B3XxZ6RNyn1sKKzrm2NtboHLbCvixVJj55xUSvIRFoLSmQkxigfT2sNRAjOyItRiz+CJYuXyk68JrC/FiIpPbeq4kIiQ8n3erCXpLdEWHvthXriKBnUdc6ECZ6SgFWuX9rr6pCVQFsiO8ihJvg2kGwe7uib3TFB8p0X5Hlfy8pxLentxSODm1S/7num1pDncHl6zaxniWKPShw834r1C8cDJ6ppJ2kixX3BUkQDk+1TY7Ht66HS1iQZWxmgfLi5hlg9LwK9dTKS+H0JE8yGNK31nhu1M3Is6PB5nnLDCxICZpzbMGTaeIHEhiATTsv+U4XeHfa3B0RFSSoMy0/skCyGMDQn6/W+iC3m5jY5dAlYeaqE5HtG6LW8W+rxkbMgzFBd2nt/IBRSLs2HWxice729fVDfwBXIvyPjaqnVgnN9D7eIO9mEXbnrI/0fhgIgy8UyfSgV6nfv5C/bCWwSJZZGWPvYGpWrPKmbBdmJDWPHdIcGTh7yGSA/fGiyGpV/NwIGkEMoIu5cvMMpxfP4bLgNA0IoGH+fFtwX84gYCFzwTKztYryYsf03qoQMSh4LvfoOqsLBoFFvRd0yLSOYcRubOinrC1QY8V7CMAupgkA7Cq5HSSrjZ+OTxD5XVgYRmFoplHpOJQDGnpPkfD/7TlZc+DievaLU=
